"""Database module."""

from database.connection import get_db_connection, init_database, reset_database
from database.queries import (
    assign_specialist,
    authenticate_user,
    cancel_order,
    create_order,
    create_product,
    create_service_request,
    create_user,
    delete_product,
    delete_service_request,
    delete_user,
    get_order_by_id,
    get_product_by_id,
    get_service_request_by_id,
    get_user_by_email,
    get_user_by_id,
    get_user_password_hash,
    list_customers,
    list_orders,
    list_product_categories,
    list_products,
    list_service_requests,
    list_specialists,
    list_users,
    update_order_status,
    update_product,
    update_service_request_status,
    update_user,
)

__all__ = [
    "get_db_connection",
    "init_database",
    "reset_database",
    "authenticate_user",
    "get_user_password_hash",
    "create_user",
    "get_user_by_id",
    "get_user_by_email",
    "list_users",
    "list_customers",
    "list_specialists",
    "update_user",
    "delete_user",
    "create_product",
    "get_product_by_id",
    "list_products",
    "list_product_categories",
    "update_product",
    "delete_product",
    "create_order",
    "get_order_by_id",
    "list_orders",
    "cancel_order",
    "update_order_status",
    "create_service_request",
    "get_service_request_by_id",
    "list_service_requests",
    "update_service_request_status",
    "assign_specialist",
    "delete_service_request",
]
